### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by CookiePLMonster** [spaceeinstein/gtalc-dinput8#1]
As of commit 1c8ada4728ca427458a7d0a47e3ebc81d5055d1d the project appears to be uncompileable. I tried building it in Debug, Release, Release (without WPO) yet all three give errors:

- `Utils.h` not present
- Unicode/Multibyte not unified between configurations

`vcversion` namespace and `Globals` appears to be missing too but I'm guessing it's supposed to be obtained from `Utils.h`.

Since MiniConsole relies on this indirectly, same issues apply there (along with some issues with how paths are set up, but that's a different thing and shouldn't affect GTA LC directly).

**Comment by spaceeinstein** [comment]
Sorry, the solution to that is to remove CHudHack.h/cpp. I haven't updated the files listing to reflect that. I don't want to outright remove those two files so I left them alone. So far I have only updated the "Release (without WPO)" configuration without updating the others. The next update will correct that.

**Comment by CookiePLMonster** [comment]
You still should remove this file - you are using version control after all, so you can recover it easily at any time!

Also, maybe it'd be a better idea to commit and push more often and only mark releases with tags? You generally should use git this way, since small and descriptive commits make it easier to track changes and contribute - a giant commit with "Updated code" message is fairly counterintuitive.

**Comment by spaceeinstein** [comment]
Is it compilable now?

**Comment by CookiePLMonster** [comment]
Yep! Thanks.
